### ISSUE TITLE
Request for  annotation_file

### ISSUE THREAD

**Issue by rezwanh001** [YMPort/MGEED#2]
Where is your `'label.csv'` file?
After reading your code we need the annotation file for execution. Do I get the exact format or this file?

**Comment by YMPort** [comment]
Thanks for your interest in this database. The "label.csv" file has been uploaded to the google drive. If you have submitted the eula, you would have a google drive link that is associated with all the data. Please just double check with that link. Thanks

**Comment by YMPort** [comment]
> Thanks for your interest in this database. The "label.csv" file has been uploaded to the google drive. If you have submitted the eula, you would have a google drive link that is associated with all the data. Please just double check with that link. Thanks



> Where is your `'label.csv'` file? After reading your code we need the annotation file for execution. Do I get the exact format or this file?

Thanks for your interest in this database. The "label.csv" file has been uploaded to the google drive. If you have submitted the eula, you would have a google drive link that is associated with all the data. Please just double check with that link. Thanks

**Comment by YMPort** [comment]
> Where is your `'label.csv'` file? After reading your code we need the annotation file for execution. Do I get the exact format or this file?

Thanks for your interest in this database. The "label.csv" file has been uploaded to the google drive. If you have submitted the eula, you would have a google drive link that is associated with all the data. Please just double check with that link. Thanks
